# Verwendet das offizielle MariaDB-Image als Basis
FROM mariadb
# Setzt Umgebungsvariablen für Benutzername und Passwort
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=db_password
# Öffnet den Datenbank-Port
EXPOSE 3306
