# Verwendet das offizielle PHP-Image mit Apache als Basis
FROM php:8.0-apache

ENV DB_HOST=kn02b-db
ENV DB_USER=root
ENV DB_PASSWORD=root_password
ENV DB_NAME=mydatabase

# Kopiert die PHP-Dateien in den entsprechenden Ordner
COPY *.php /var/www/html/

# Installiert das PHP mysqli-Modul
RUN docker-php-ext-install mysqli

# Call db.php during the build process to configure it
#For test
# RUN php -f /var/www/html/db.php > /var/www/html/db_output.html

EXPOSE 80