# Verwendet das offizielle nginx-Image als Basis
FROM nginx

# Setzt das Workdirectory auf /usr/share/nginx/html
WORKDIR /usr/share/nginx/html

# Kopiert den Inhalt von static-html-directory ins Arbeitsverzeichnis im Container
COPY helloworld.html .

# Öffnet Port 80 im Container für eingehende HTTP-Anfragen
EXPOSE 80
