#cloud-config
# source: https://thenewstack.io/deploy-a-kubernetes-cluster-on-ubuntu-server-with-microk8s/
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, microk8s
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUBo+qnNu5xxM9vfz4C04M36FHxHNrEMdm5TkFj1/SfVtqunlUOeMpu7nFCZZKnX8HYwf/MkjcBiTYAgncxku8grwl6XuW/pcvmb6/ghSIaw4xtRRSzit7omqJ5d8kXB3+Nd1aaMHsjfly4nkaqswhySVXQqr8Hw6DbWVw8jLLVKEE+5NZHY33hJkhJwK4blCllsGpmQaKi1qxjsN0hZOWNK01iJAydwD8t2xJ0NOYbq8Qas5IyPnRN7SPxvEhIP6WLQ6Ym6Dmf8FwNW1cHLTKabgjzt5f/HKUkKS89dPd3fn4nnFli1BOMECGUIvVlOw2pQNri7+04OOfn2FGlqr5
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCg/6fE3M1VVR9xU82WbM0QxyT7XQ4J55jPYKa46meiCJOKjeLF8pkGbqvDUeKflD77rBrXqSJIROFJAgXWjYq52yt9kgcEMDb67xAHw0+QZFtjd2zpEq9PlWVnPiRBsthHKdxr5ilykuiI/yAf2q9Pt7I0QL2WmMmF6FJkgMn+2t++FBoHbQ+c31PwqW0XUjbv88gOobVcx2uMmcTo1KAVsSei2LU0tYEFyIZoBTaxbHY3cO3yERDnkw9hgL+hmJ7oyXknJyLLHIQJw2kX67m+DTHXsOeY93JsSa0CVm/pstRPoN2B8beneFZlv48u3mx1uyL2MzGzogq3Y3HBEzKv
groups:
  - microk8s
system_info:
  default_user:
    groups: [microk8s]
ssh_pwauth: false
disable_root: false
package_update: true
package_upgrade: true
packages:
  - curl
runcmd:
  - sudo snap install microk8s --classic
  - mkdir /home/ubuntu/.kube
