#cloud-config
# source: https://thenewstack.io/deploy-a-kubernetes-cluster-on-ubuntu-server-with-microk8s/
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, microk8s
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUBo+qnNu5xxM9vfz4C04M36FHxHNrEMdm5TkFj1/SfVtqunlUOeMpu7nFCZZKnX8HYwf/MkjcBiTYAgncxku8grwl6XuW/pcvmb6/ghSIaw4xtRRSzit7omqJ5d8kXB3+Nd1aaMHsjfly4nkaqswhySVXQqr8Hw6DbWVw8jLLVKEE+5NZHY33hJkhJwK4blCllsGpmQaKi1qxjsN0hZOWNK01iJAydwD8t2xJ0NOYbq8Qas5IyPnRN7SPxvEhIP6WLQ6Ym6Dmf8FwNW1cHLTKabgjzt5f/HKUkKS89dPd3fn4nnFli1BOMECGUIvVlOw2pQNri7+04OOfn2FGlqr5 teacher
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCWKgo034v0YU3OJ55lswRlLNb9UOKMhHxqcYEzxJ94mfoo/LIhkJLYDwBGHZOiVaouioBWuYr8e/64YGmIxC8zY8qslLC/HJSKcwoxZINNO436l3+jX5R8B2qJa3yovGv+br02M6LcHsl1MwJMU17yYBuohqPa4q5IvOYE+lQwoXRc4k1Q+poKyLV28QTvMJIkLZL7zlrZlmkKBxkpMjc6brfxj2KYtM+E0hUkelB1BP7m7m5o1LjXML7TRsD+RR8CpPghW/7xHkrPPg1IljF2l5a/n2oDAQv2NvUnQpl+9nJCmbu20l3LWgzeiOgdZtQ7efk+UnatMd1cbHS/C0j7
groups:
  - microk8s
system_info:
  default_user:
    groups: [microk8s]
ssh_pwauth: false
disable_root: false
package_update: true
package_upgrade: true
packages:
  - curl
runcmd:
  - sudo snap install microk8s --classic
  - mkdir /home/ubuntu/.kube
